# Array operations with NumPy

In this notebook we'll explore how NumPy arrays make math operations fast and easy:

- Element-wise operations
- Broadcasting
- Comparison to Python Lists

### Element wise operations

In [1]:
import numpy as np

In [2]:
a_arr = np.array([1, 2, 3, 4])
b_arr = np.array([10, 20, 30, 40])

print(a_arr)
print(b_arr)

[1 2 3 4]
[10 20 30 40]


In [6]:
# element wise operations
print(a_arr + b_arr)
print(a_arr - b_arr)
print(a_arr * b_arr)
print(a_arr / b_arr)
print(a_arr ** 2) # square each element in a_arr
print(np.sqrt(a_arr)) # square root using sqrt method

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]


### Broadcasting

Broadcasting allows operations between arrays of different shapes.

NumPy automatically "expands" arrays when possible.

In [8]:
my_arr = np.array([1, 2, 3, 4, 5])

print("arr + 10:", my_arr + 10)

arr + 10: [11 12 13 14 15]


In [9]:
print("arr multiplied by 2:", my_arr * 2)

arr multiplied by 2: [ 2  4  6  8 10]


In [10]:
mat = np.array([[1, 2, 3],[4, 5, 6]])
print(mat + np.array([10, 20, 30]))

[[11 22 33]
 [14 25 36]]


### Comparing NumPy arrays to Python lists

In [13]:
import time

size = 10_000_000

# Python list
L = list(range(size))
start = time.time()
L2 = [x * 2 for x in L]
print("Python list time:", time.time() - start)

# NumPy array
A = np.arange(size)
start = time.time()
A2 = A * 2
print("NumPy array time:", time.time() - start)

Python list time: 4.381453275680542
NumPy array time: 0.13744401931762695
