# Numpy Intro

In [1]:
print("Hello World")

Hello World


In [12]:
import numpy as np

Create a list of numbers

In [1]:
numbers = [1, 2, 3, 4, 5]

Turn it into a NumPy array:

In [14]:
array = np.array(numbers)

In [16]:
doubled = array * 2
print(doubled)

[ 2  4  6  8 10]


Built in array creation

In [18]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
ones = np.ones((3))
print(ones)

[1. 1. 1.]


In [21]:
range_array = np.arange(0, 20, 2)
print(range_array)

[ 0  2  4  6  8 10 12 14 16 18]


In [24]:
one_to_ten_array = np.arange(11)
print(one_to_ten_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


### Indexing and Slicing

In [27]:
arr = np.array([10, 20, 30, 40, 50])

# Indexing
print(arr[0])
print(arr[-1])

# Slicing
print(arr[0:3])
print(arr[::2])

10
50
[10 20 30]
[10 30 50]


In [29]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two_d_array[0, 1]) # 0 = first array, 1 = second index of that array --> "2"

2


In [33]:
print(two_d_array[1, :]) # second array, entire array

[4 5 6]


### Array Attributes

In [34]:
arr = np.arange(12).reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
# Check array shape
print(arr.shape)

(3, 4)


In [38]:
# Check dimensions
print(arr.ndim)

2


In [39]:
# Check data type
print(arr.dtype)

int64


In [40]:
# Check size
print(arr.size)

12


### Slicing and Reshaping

In [41]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
# reshape array without changing contents (3 x 4)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
# Flatten a multi-dimensional array
flattened_arr = reshaped_arr.ravel()
print(flattened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
