In [1]:
import numpy as np

### 3d arrays

In [3]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


### Iteration through arrays

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
for num in arr1:
    print(num)

1
2
3
4
5


In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
for array in arr2:
    for num in array:
        print(num)

1
2
3
4
5
6
