# Numpy statistical functions and the random module

In [9]:
import numpy as np

In [19]:
# Random integers
dice = np.random.randint(1, 7, size=10) # 10 dice rolls
print("Dice rolls:", dice)

# Random floats
rand_floats = np.random.rand(5)
print(rand_floats)

# random normal distribution
norm_samples = np.random.randn(5) # mean=0 std=1
print(norm_samples)

Dice rolls: [5 4 2 4 5 5 6 3 1 1]
[0.90281053 0.85620284 0.81864438 0.54942586 0.74709109]
[-0.03341028 -1.08899849  1.11401814  0.9037775  -1.01343515]


### Statistical functions

NumPy makes calculating statistics easy!

In [20]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))

Sum: 55
Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Minimum: 1
Maximum: 10


In [27]:
data_2d = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

print("Sum:", np.sum(data_2d))
print("Mean:", np.mean(data_2d))
print("Median:", np.median(data_2d))
print("Std:", np.std(data_2d))

Sum: 210
Mean: 10.5
Median: 10.5
Std: 5.766281297335398


### Reshaping and stacking arrays

In [30]:
# Reshape
arr_1 = np.arange(12)
print(arr_1)

arr_2 = arr_1.reshape(3, 4)
print(arr_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
# Stacking arrays
stack1 = np.array([1, 2, 3])
stack2 = np.array([4, 5, 6])
vstacked = np.vstack([stack1, stack2]) # vertical stacking --> i.e. dimensions
print(vstacked)
hstacked = np.hstack([stack1, stack2]) # horizontal stacking --> i.e. add arrays into 1 long array
print(hstacked)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
